apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: back
    app.kubernetes.io/name: nest-http-server
    app.kubernetes.io/part-of: httpServer
  name: nest-http-server
  namespace: nest-http
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: back
      app.kubernetes.io/name: nest-http-server
      app.kubernetes.io/part-of: httpServer
  template:
    metadata:
      labels:
        app.kubernetes.io/component: back
        app.kubernetes.io/name: nest-http-server
        app.kubernetes.io/part-of: httpServer
    spec:
      containers:
        - image: ghcr.io/andes-noh/nest-http-app:9e830286
          name: app
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: "0.2"
              memory: 128M
