apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: back
    app.kubernetes.io/name: nest-http-server
    app.kubernetes.io/part-of: httpServer
  name: nest-http-server
  namespace: nest-http
spec:
  ports:
    - nodePort: 32755
      port: 3000
      targetPort: 3000
  selector:
    app.kubernetes.io/component: back
    app.kubernetes.io/name: nest-http-server
    app.kubernetes.io/part-of: httpServer
  type: NodePort
